name = "Алижонов Самандар Xудойберди Угли "
description = "Менеджер по продажам в компании VAN UNIVERSAL MOTORS"
keywords = ""
image = "Без имени-1.jpg"
theme = "light"
primary_color = "#292c35"
text_align = "center"
gtag_id = ""
base_url = "https://biloliddinabdujalilov.github.io/samandar/"

[[sections]]
title = "Контакты"
description = "+998932284402"
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/tzYdqMRJntk?si=3yLTORA7CZQMXh33"
[[sections.items]]
title = "Telegram"
description = "@Cardiosurgion_Samandar"
url = "https://t.me/Cardiosurgion_Samandar"
[[sections.items]]
title = "WhatsApp"
description = "+998932284402"
url = "https://wa.me/998932284402"
[[sections.items]]
title = "E-mail"
description = "alijonovsamandar2003@gmail.com"
url = "mailto:alijonovsamandar2003@gmail.com"


[[sections]]
title = "Ссылки"
description = "Социальные сети компании VUM"
direction = "row"
item_style = "outline"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram"
title = "Instagram"
url = "https://www.instagram.com/vum_faw_uzbekistan"
[[sections.items]]
icon = "https://cdn.simpleicons.org/youtube"
title = "YouTube"
url = "https://www.youtube.com/@faw_uzbekistan/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/google"
title = "Сайт"
url = "https://faw.uz"
[[sections.items]]
title = "Facebook"
icon = "https://cdn.simpleicons.org/facebook"
url = "https://www.facebook.com/fawuzbekistan"
